//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrinkManagerWeb.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HomeTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HomeTexts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DrinkManagerWeb.Resources.HomeTexts", typeof(HomeTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Favourites.
        /// </summary>
        public static string Add_to_Favourites {
            get {
                return ResourceManager.GetString("Add to Favourites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alcohol content:.
        /// </summary>
        public static string Alcohol_content_ {
            get {
                return ResourceManager.GetString("Alcohol content:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All drinks.
        /// </summary>
        public static string All_drinks {
            get {
                return ResourceManager.GetString("All drinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Drink.
        /// </summary>
        public static string Create_New_Drink {
            get {
                return ResourceManager.GetString("Create New Drink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drink list.
        /// </summary>
        public static string Drink_list {
            get {
                return ResourceManager.GetString("Drink list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favourite drinks.
        /// </summary>
        public static string Favourite_drinks {
            get {
                return ResourceManager.GetString("Favourite drinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glass:.
        /// </summary>
        public static string Glass_ {
            get {
                return ResourceManager.GetString("Glass:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go back.
        /// </summary>
        public static string Go_back {
            get {
                return ResourceManager.GetString("Go back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingredients.
        /// </summary>
        public static string Ingredients {
            get {
                return ResourceManager.GetString("Ingredients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review.
        /// </summary>
        public static string Review {
            get {
                return ResourceManager.GetString("Review", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reviewed drinks.
        /// </summary>
        public static string Reviewed_drinks {
            get {
                return ResourceManager.GetString("Reviewed drinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by alcohol content.
        /// </summary>
        public static string Search_by_alcohol_content {
            get {
                return ResourceManager.GetString("Search by alcohol content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by ingredient.
        /// </summary>
        public static string Search_by_ingredient {
            get {
                return ResourceManager.GetString("Search by ingredient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by name.
        /// </summary>
        public static string Search_by_name {
            get {
                return ResourceManager.GetString("Search by name", resourceCulture);
            }
        }
    }
}
