//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrinkManagerWeb.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DrinkManagerWeb.Resources.SharedResource", typeof(SharedResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to alcohol content.
        /// </summary>
        public static string alcohol_content {
            get {
                return ResourceManager.GetString("alcohol content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alcoholic drinks.
        /// </summary>
        public static string AlcoholicDrinks {
            get {
                return ResourceManager.GetString("AlcoholicDrinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Drinks.
        /// </summary>
        public static string AllDrinks {
            get {
                return ResourceManager.GetString("AllDrinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All ingredients.
        /// </summary>
        public static string AllIngredients {
            get {
                return ResourceManager.GetString("AllIngredients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any ingredient.
        /// </summary>
        public static string AnyIngredient {
            get {
                return ResourceManager.GetString("AnyIngredient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose alcoholic option.
        /// </summary>
        public static string ChooseAlcoholicOption {
            get {
                return ResourceManager.GetString("ChooseAlcoholicOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new account.
        /// </summary>
        public static string CreateANewAccount {
            get {
                return ResourceManager.GetString("CreateANewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new drink.
        /// </summary>
        public static string CreateNewDrink {
            get {
                return ResourceManager.GetString("CreateNewDrink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drink List.
        /// </summary>
        public static string DrinkList {
            get {
                return ResourceManager.GetString("DrinkList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a drink name to find.
        /// </summary>
        public static string EnterADrinkNameToFind {
            get {
                return ResourceManager.GetString("EnterADrinkNameToFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter ingredients to find.
        /// </summary>
        public static string EnterIngredientsToFind {
            get {
                return ResourceManager.GetString("EnterIngredientsToFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favourite drinks.
        /// </summary>
        public static string FavouriteDrinks {
            get {
                return ResourceManager.GetString("FavouriteDrinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favourite drinks list.
        /// </summary>
        public static string FavouriteDrinksList {
            get {
                return ResourceManager.GetString("FavouriteDrinksList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ingredients.
        /// </summary>
        public static string ingredients {
            get {
                return ResourceManager.GetString("ingredients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name.
        /// </summary>
        public static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No favourite drinks yet.
        /// </summary>
        public static string NoFavouriteDrinksYet {
            get {
                return ResourceManager.GetString("NoFavouriteDrinksYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non alcoholic drinks.
        /// </summary>
        public static string NonAlcoholicDrinks {
            get {
                return ResourceManager.GetString("NonAlcoholicDrinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No reviewed drinks yet.
        /// </summary>
        public static string NoReviewedDrinksYet {
            get {
                return ResourceManager.GetString("NoReviewedDrinksYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional alcohol drinks.
        /// </summary>
        public static string OptionalAlcoholDrinks {
            get {
                return ResourceManager.GetString("OptionalAlcoholDrinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ratings.
        /// </summary>
        public static string ratings {
            get {
                return ResourceManager.GetString("ratings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register with Facebook.
        /// </summary>
        public static string RegisterWithFacebook {
            get {
                return ResourceManager.GetString("RegisterWithFacebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register with Google.
        /// </summary>
        public static string RegisterWithGoogle {
            get {
                return ResourceManager.GetString("RegisterWithGoogle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reviewed drinks.
        /// </summary>
        public static string ReviewedDrinks {
            get {
                return ResourceManager.GetString("ReviewedDrinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reviewed drinks list.
        /// </summary>
        public static string ReviewedDrinksList {
            get {
                return ResourceManager.GetString("ReviewedDrinksList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to review to drinks.
        /// </summary>
        public static string reviewToDrinks {
            get {
                return ResourceManager.GetString("reviewToDrinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by alcohol content.
        /// </summary>
        public static string SearchByAlcoholContent {
            get {
                return ResourceManager.GetString("SearchByAlcoholContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by ingredients.
        /// </summary>
        public static string SearchByIngredients {
            get {
                return ResourceManager.GetString("SearchByIngredients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by name.
        /// </summary>
        public static string SearchByName {
            get {
                return ResourceManager.GetString("SearchByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tip 1: you can provide one or more ingredients separated by a space.
        /// </summary>
        public static string Tip1ToSearchByIngredients {
            get {
                return ResourceManager.GetString("Tip1ToSearchByIngredients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tip 2: choose if you want to find drinks containing ANY or ALL provided ingredients.
        /// </summary>
        public static string Tip2ToSearchByIngredients {
            get {
                return ResourceManager.GetString("Tip2ToSearchByIngredients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tip: you can provide a part of the name you are looking for.
        /// </summary>
        public static string TipToSearchByName {
            get {
                return ResourceManager.GetString("TipToSearchByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use another service to register.
        /// </summary>
        public static string UseAnotherServiceToRegister {
            get {
                return ResourceManager.GetString("UseAnotherServiceToRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome in Drink Manager App.
        /// </summary>
        public static string WelcomeInDrinkManagerApp {
            get {
                return ResourceManager.GetString("WelcomeInDrinkManagerApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When you find your beloved drink you can add it to your list of favourite drinks.
        /// </summary>
        public static string WhenYouFindYourBelovedDrink {
            get {
                return ResourceManager.GetString("WhenYouFindYourBelovedDrink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With this app you can search drinks by their.
        /// </summary>
        public static string WithThisAppYouCanSearchDrinksByTheir {
            get {
                return ResourceManager.GetString("WithThisAppYouCanSearchDrinksByTheir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can also add.
        /// </summary>
        public static string YouCanAlsoAdd {
            get {
                return ResourceManager.GetString("YouCanAlsoAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your drink.
        /// </summary>
        public static string yourDrink {
            get {
                return ResourceManager.GetString("yourDrink", resourceCulture);
            }
        }
    }
}
